### ISSUE TITLE
String measure routines.

### ISSUE THREAD

**Issue by gabrielaexile** [michaelrsweet/pdfio#17]
Will there be string measure routines like in libharu ?

And thank you for starting this project, there has been a lot of need for such after libharu went stale.

**Comment by michaelrsweet** [comment]
@gabrielaexile I can look at adding them, but the current text handling capabilities in PDFio are intentionally limited since doing proper Unicode rendering is more complicated than drawing each of the glyphs. My initial intent is for PDFio to provide the low-level support so that higher-level libraries can use it to handle the complex details of supporting the PDF format itself.

**Comment by michaelrsweet** [comment]
Oh, and FWIW my mini TrueType/OpenType library (embedded in PDFio and available [separately](https://github.com/michaelrsweet/ttf) can be used to get the extents of a string for a given font. I'm using this in HTMLCSS as well (which will ultimately be used with PDFio when I get around to doing a greatly enhanced version of HTMLDOC...)
