### ISSUE TITLE
Modifying PDFs

### ISSUE THREAD

**Issue by B83C** [michaelrsweet/pdfio#28]
**Is your feature request related to a problem? Please describe.**
I have been looking for a PDF manipulation library in C but PDFio seems to be the only one that can be built without errors and is up-to-date. However, the lack of the ability to edit existing PDF files held me back. Looking at documentation, there doesn't seem to be any avenue of editing PDFs with it, only read/write.

**Describe the solution you'd like**
Implement the feature of editing given PDFs. 

**Describe alternatives you've considered**
VersyPDF but the entire thing doesn't build at all and is quite old with virtually no examples in the doc.

**Additional context**
NULL

**Comment by michaelrsweet** [comment]
@B83C i assume you mean you want to update a PDF file in place as opposed to simply creating a new PDF and copying the content over? That’s not something I planned on supporting, partly because there are a lot of edge cases that force creation of a new file anyways and partly because it is a security and privacy nightmare.

What exactly do you want to be able to do?

**Comment by B83C** [comment]
Doing modifications such as adding texts to a given page which is what I desperately need for my project.

**Comment by michaelrsweet** [comment]
OK, so that *is* possible with the current PDFio library - you'll need to add your own fonts/etc. when copying each page's dictionary, and then copy the page stream data from the source file to your new PDF file, appending your modifications along the way. I'll see about adding an example that watermarks pages in a PDF.

**Comment by B83C** [comment]
Alright, I will try it out. Thanks for suggesting!

**Comment by saveliyvasilev** [comment]
> [@B83C](https://github.com/B83C) i assume you mean you want to update a PDF file in place as opposed to simply creating a new PDF and copying the content over? That’s not something I planned on supporting, partly because there are a lot of edge cases that force creation of a new file anyways and partly because it is a security and privacy nightmare.
> 
> What exactly do you want to be able to do?

Hi @michaelrsweet , answering here since it feels right.

A bit of context about what I'm trying to do: load the document from a buffer, add annotations, fill forms, create appearance streams, delete some pages, and then return the document in a buffer. I'm talking about buffers and not files since one of the compilation targets I need is WebAssembly, to be executed from a browser. Ideally this would be pure C code as I've had weird problems when using C++.

As of now, two approaches come to mind, happy to hear your thoughts about these:

1. Use `pdfio` mostly as it is. I thought of injecting some memory-backed `FILE` (I believe `fmemopen` is a good starting point). But before doing this I tried to do a basic form filling: played a bit with the idea of adjusting some dictionaries and cloning the document, but so far I didn't quite succeed. Definitely an example would be handy, especially if it creates a new `XObject` which is then used as a `/AP -> /N` appearance stream for an existing `Tx` widget. I feel that `pdfioPageCopy` is too high level for this since objects are closed for edition after the copy. If my feeling is correct, then the approach should do some sort of manual deep-copy with in-flight modifications. Does this sound about right?
2. A more radical fork of `pdfio`: essentially, creating an in-memory model of the PDF file, support in-place modifications, and then write it in an orderly fashion to a buffer with a logic to resolve references, encodings and that kind of stuff. Definitely not a quick path to success here. I wonder if you could go a bit deeper in the "a lot of edge cases that force creation of a new file" and "security nightmare" comment you did before, or, for that matter, any other warning that comes to your mind.

Thanks in advance, all the best!

**Comment by saveliyvasilev** [comment]
After giving this another thought, another option would be to add new objects to the file with a hand-provided obj num and generation; and then adjust the xref writing code to include the obj num and generation before the offset of the new objects (or adding an entirely new xref + trailer block).

**Comment by michaelrsweet** [comment]
@saveliyvasilev One (major) issue with modifying an existing PDF file is that you need to preserve the same line endings as the original content, very carefully update/replace objects and dictionaries as needed, and pray that you are not using any PDF features that are incompatible with the original PDF.

The PDFio API allows you to copy content from one PDF to another, including whole pages and their resources (`pdfioPageCopy`) in a way that doesn't duplicate data in the destination PDF. That will yield a new, clean PDF which is far less likely to fail/get corrupted along the way.

As for how to "port" PDFio to WebAssembly, I have no experience doing so and (with respect) have my doubts about the performance and security of such a solution...

**Comment by saveliyvasilev** [comment]
@michaelrsweet Those are some insights that weren't on my radar, thanks a ton!
