### ISSUE TITLE
vikings.pdf: Cross-reference stream has invalid W key.

### ISSUE THREAD

**Issue by kleuter** [michaelrsweet/pdfio#46]
The pdfiototext tool fails to parse the file:
https://www.dropbox.com/scl/fi/xpktv4rrozm22sxjuyarp/vikings.pdf?rlkey=e6rdkbbgjg45d2mfypdrjwd8a&dl=0

**System Information:**
 - OS: Windows 10, Visual Studio 2019

**Comment by michaelrsweet** [comment]
OK, so this file, generated by some sort of Microsoft project, contains a cross reference stream with a W value of [1 4 3]. The third value specifies the size of the "generation number" field in bytes, where the generation number is an integer between 0 and 65535. Normally this field should be 1 or 2 bytes in length (1 allows generation numbers from 0 to 255, 2 allows the full range of 0 to 65535). Having anything larger is puzzling, but since other PDF consuming applications seem to deal with this OK I'll just allow it and peg values > 65535 as required by the PDF standards.

**Comment by michaelrsweet** [comment]
This file also has empty binary (hex) strings...

[master 7f6ffcd] Fix a couple issues with parsing PDF files produced by Microsoft Reporting Services (Issue #46)

**Comment by kleuter** [comment]
thanks, Michael!
