### ISSUE TITLE
Switch to autoconf/configure

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/pdfio#54]
Based on some feedback (see #53) about issues with the current portable makefile build system, switch to using autoconf to create a configure script that handles generating the makefile. Specific goals:

- Provide control over build commands and specific installation directories
- Detect the appropriate version of zlib to use (use pkg-config then fall back on basic library check)
- Choose whether to build static and/or shared libraries
- Support cross-compilation
- Support out-of-tree builds (i.e. a separate build directory)

**Comment by michaelrsweet** [comment]
@eli-schwartz I actually don't have any experience using the PKG_CHECK_MODULES macro, primarily because it isn't part of autoconf. It requires the use of aclocal (or you need to AC_INCLUDE the pkg.m4 file in the aclocal directory), not to mention the pkg.m4 file is provided under the GPLv2 which isn't compatible with PDFio's Apache 2.0 library (sigh...)

**Comment by eli-schwartz** [comment]
> not to mention the pkg.m4 file is provided under the GPLv2 which isn't compatible with PDFio's Apache 2.0 library (sigh...)

This turns out to not be the case. For two reasons.

Autoconf is also GPL software, but GPL 3, which is compatible with Apache 2.

The pkg.m4 is "either version 2 of the License, or (at your option) any later version.", a fairly common way to use the GPL2 that permits projects such as PDFio to accept it under the GPL3 license terms. It is not Apache, but it is *compatible*.


But also, there is a special exception clause in autoconf itself, which means you don't need to be compatible with the GPL3 *either* and you can still ship a generated configure script and its config.sub/config.guess and related software:
https://github.com/michaelrsweet/pdfio/blob/c992b2ba8900238c3a50f26dcdab34b4ee8296a7/config.guess#L9-L27

And pkg.m4 has the same exception clause. It was part of the initial addition of licensing terms in https://gitlab.freedesktop.org/pkg-config/pkg-config/-/commit/b1584b5aaf9ce396e61599caff2b5e15f01daf91 from 2004.

```
dnl As a special exception to the GNU General Public License, if you
dnl distribute this file as part of a program that contains a
dnl configuration script generated by Autoconf, you may include it under
dnl the same distribution terms that you use for the rest of that
dnl program.
```
